W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]
end

W7D2/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

W7D2/music_app/app/models/band.rb
class Band < ApplicationRecord
end

W7D2/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  
  validates :email, presence:true, uniqueness:true
  validates :password_digest, presence:true
  validates :session_token, presence:true, uniqueness:true
  validates :password, length: {minimum:6}
  
  after_initialize :ensure_session_token

def self.generate_session_token
  SecureRandom::urlsafe_base64
end

def self.find_by_credentials(email, password)
  user = User.find_by(email: email)
  if user && user.is_password?(password)
    user
  else
    nil
  end
end

def reset_session_token!
  self.session_token = User.generate_session_token
  self.save!
  self.session_token
end

def ensure_session_token
  self.session_token ||= User.generate_session_token
end

def password=(password)
  self.password_digest = BCrypt::Password.create(password)
  @password = password
end

def is_password?
  BCrypt::Password.new(self.password_digest).is_password?(password)
end

end

W7D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :login!

def login!(user)
  session[:session_token] = user.reset_session_token!
end

def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
end

def logged_in?
  !!current_user
end

def logout!
  current_user.reset_session_token if logged_in?
  session[:session_token] = nil
  @current_user = nil
end

def require_logged_in
  redirect_to new_session_url unless logged_in?
end

end

W7D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  render :new
end

def create
  user = User.find_by_credentials(params[:user][:email], params[:user][:password])
  if user
    login!(user)
    redirect_to users_url
  else
    render :new
  end
end

def destroy
  logout!
  redirect_to new_session_url 
end

end

W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  render :new
end

def create
 @user = User.new(user_params)
  if @user.saves!
    login!(user)
    redirect_to users_url
  else
    render :new
  end
end

def show
  @users = User.find_by(id: params[:id])
  if @user
    render :show
  else
    redirect_to users_url
  end
end

private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

W7D2/music_app/app/views/users/_form.html.erb
<% if type == 'new' %>
  <% action_url = users_url %>
  <% button_text = 'Create User' %>
<% else %>
  <% action_url = user_url(user) %>
  <% button_text = 'Edit User' %>
<% end %>


<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if type == 'edit' %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>Email:
    <input type="text" name="user[email]" value="<%= user.email %>">
  </label>
  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="<%= button_text %>">
</form>

W7D2/music_app/app/views/users/_user.html.erb
<% if action == 'show' %>
  <a href="<%= users_url %>">Users Index Link</a>
<% else %>
  <a href="<%= user_url(user.id) %>">User Show Page</a>
<% end %>

<ul>
  <li><%= user.email %></li>
</ul>

W7D2/music_app/app/views/users/edit.html.erb
<h1>Edit User Form</h1>
<%= render 'form', type: 'edit', user: @user %>

W7D2/music_app/app/views/users/index.html.erb
<h1>Here are all of our USERS!</h1>
<a href="<%= new_user_url %>">Create a new User</a>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= render "user",  user: user, action: 'index' %>
    </li>
  <% end %>
</ul>

W7D2/music_app/app/views/users/new.html.erb
<h1>New User Form</h1>
<%= render 'form', type: 'new', user: @user %>

W7D2/music_app/app/views/users/show.html.erb
  
<%#render('user', {user: @user})%>
<%= render "user",  user: @user, action: 'show' %>

<a href="<%= edit_user_url(@user) %>">Edit User</a>

<form action="<%= user_url(@user) %>" method="POST" >
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete User">
</form>